# =============================================================================
# EXAMPLE: Pipeline Secrets - DO NOT COMMIT ACTUAL VALUES TO GIT
# =============================================================================
# This secret contains credentials for the CI/CD pipeline setup.
# The initialize-namespace Job reads from this secret to configure Tekton pipelines.
#
# Create this secret in your deployment namespace:
#
# Option 1: Using kubectl
# ------------------------
# kubectl create secret generic pipeline-secrets \
#   --from-literal=GIT_TOKEN=<your-git-pat> \
#   --from-literal=GITLAB_TOKEN=<your-gitlab-pat> \
#   --from-literal=WEBHOOK_SECRET=<your-webhook-secret> \
#   --from-literal=QUAY_DOCKERCONFIGJSON=<base64-dockerconfig> \
#   -n <your-namespace>
#
# Option 2: Using this YAML (for reference only - don't commit real values!)
# ---------------------------------------------------------------------------
# kubectl apply -f pipeline-secrets-example.yaml -n <your-namespace>
#
# NOTE: All fields are optional. The pipeline will skip setup for missing values.
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets  # Use the name you provided in the template
  labels:
    app.kubernetes.io/component: pipeline
type: Opaque
stringData:
  # GitHub/GitLab Personal Access Token for GitOps operations
  # Required for: gitops-auth-secret (pushing to GitOps repository)
  # Scopes needed: repo (full access to repositories)
  GIT_TOKEN: ""
  
  # GitLab Personal Access Token (only if using GitLab)
  # Required for: gitlab-auth-secret
  # Scopes needed: api, read_repository, write_repository
  GITLAB_TOKEN: ""
  
  # Pipelines as Code webhook secret
  # Required for: pipelines-secret
  # Generate with: openssl rand -hex 20
  WEBHOOK_SECRET: ""
  
  # Quay/Image Registry dockerconfigjson (base64 encoded)
  # Required for: rhdh-image-registry-token
  # Generate with:
  #   kubectl create secret docker-registry temp \
  #     --docker-server=quay.io \
  #     --docker-username=<user> \
  #     --docker-password=<token> \
  #     --dry-run=client -o jsonpath='{.data.\.dockerconfigjson}'
  QUAY_DOCKERCONFIGJSON: ""
  
  # NOTE: Cosign public key is automatically fetched from openshift-pipelines namespace
  # (from signing-secrets secret) - no user entry required!
