# =============================================================================
# EXAMPLE SECRETS - DO NOT COMMIT ACTUAL VALUES TO GIT
# =============================================================================
# This file shows the structure of secrets you need to create manually.
# Create these secrets in your deployment namespace before or after running
# the template.
#
# Option 1: Using kubectl
# ------------------------
# kubectl create secret generic llama-stack-secrets \
#   --from-literal=VLLM_API_KEY=<your-vllm-api-key> \
#   --from-literal=OPENAI_API_KEY=<your-openai-api-key> \
#   -n <your-namespace>
#
# kubectl create secret generic app-secrets \
#   --from-literal=GITHUB_TOKEN=<your-github-pat> \
#   -n <your-namespace>
#
# Option 2: Using Sealed Secrets (for GitOps)
# -------------------------------------------
# 1. Create the secret YAML locally (don't commit!)
# 2. Seal it with kubeseal
# 3. Commit the sealed secret
#
# Option 3: Using External Secrets Operator
# -----------------------------------------
# Reference secrets from AWS Secrets Manager, HashiCorp Vault, etc.
# =============================================================================

---
# Secret 1: Llama Stack Secrets
# Required for the Llama Stack inference server
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-secrets  # Use the name you provided in the template
  labels:
    app.kubernetes.io/component: llama-stack
type: Opaque
stringData:
  # API key for vLLM server (required)
  VLLM_API_KEY: "<your-vllm-api-key>"
  
  # OpenAI API key for embeddings (required)
  OPENAI_API_KEY: "<your-openai-api-key>"

---
# Secret 2: Application Secrets
# Required for the Streamlit application
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets  # Use the name you provided in the template
  labels:
    app.kubernetes.io/component: streamlit-ui
type: Opaque
stringData:
  # GitHub Personal Access Token (required)
  # Create at: https://github.com/settings/tokens
  # Required scopes: repo (for issue creation and comments)
  # See: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  GITHUB_TOKEN: "<your-github-personal-access-token>"
